# Generated by Django 5.1.4 on 2025-01-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storagedeals_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagedeals',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storageowner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storageownergigs',
            options={'ordering': ['-title']},
        ),
    ]
