# Generated by Django 5.1.4 on 2025-01-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_alter_farmergigs_options_farmergigs_quantity'),
        ('storage', '0005_storageownergigs_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageownergigs',
            name='prefered_crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.crops'),
        ),
    ]
