# Generated by Django 5.1.4 on 2025-01-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storageownergigs_prefered_crop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageownergigs',
            options={'ordering': ['-price']},
        ),
        migrations.RenameField(
            model_name='storageownergigs',
            old_name='title',
            new_name='address',
        ),
    ]
