# Generated by Django 5.1.4 on 2025-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_storageownergigs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageownergigs',
            name='is_Available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storageownergigs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_gigs/'),
        ),
    ]
