# Generated by Django 5.1.4 on 2024-12-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.BigIntegerField(blank=True, null=True)),
                ('consultation_id', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_type', models.CharField(choices=[('Gig', 'Gig Review'), ('Consultation', 'Consultation Feedback'), ('General', 'General Feedback')], default='General', max_length=50)),
            ],
        ),
    ]
