# Generated by Django 5.1.4 on 2024-12-31 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentitems',
            name='rent_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentowner'),
        ),
        migrations.AddField(
            model_name='rentitemgigs',
            name='rent_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentowner'),
        ),
    ]
