# Generated by Django 5.1.4 on 2025-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitemgigs',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentitemgigs',
            name='is_ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentitems',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
