# Generated by Django 5.1.4 on 2025-01-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentitemgigs_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitemgigs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_gigs/'),
        ),
        migrations.AlterField(
            model_name='rentitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_items/'),
        ),
    ]
