# Generated by Django 5.1.4 on 2025-01-14 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rentitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitemorders',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
