# Generated by Django 5.1.4 on 2025-01-14 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rentitemorders_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitemorders',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
