# Generated by Django 5.1.4 on 2025-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
        migrations.AlterField(
            model_name='farmergigs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_gigs/'),
        ),
    ]
