# Generated by Django 5.1.4 on 2025-01-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_crops_image_alter_farmer_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmergigs',
            options={'ordering': ['id']},
        ),
    ]
