# Generated by Django 5.1.4 on 2025-01-09 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_farmergigs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmergigs',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='farmergigs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
