# Generated by Django 5.1.4 on 2025-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_farmergigs_options_farmergigs_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmergigs',
            options={'ordering': ['created_at', 'quantity']},
        ),
        migrations.AddField(
            model_name='farmergigs',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
